services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: users-zookeeper
    restart: always
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=1000
    ports:
      - 2181:2181
    networks:
      - users-kafka-net
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: users-kafka
    restart: always
    depends_on: 
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - users-kafka-net
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    container_name: users-kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: user-service-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9093
    networks:
      - users-kafka-net

networks:
  users-kafka-net:
    driver: bridge
